apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app
spec:
  url: https://github.com/alexellis/env-flux.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env
spec:
  sourceRef:
    kind: GitRepository
    name: env
  path: ./apps/prod
