apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: env-repo
spec:
  url: https://github.com/alexellis/env-flux.git
  interval: 5m
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env
spec:
  interval: 10m
  targetNamespace: openfaas-fn
  sourceRef:
    kind: GitRepository
    name: env-repo
  path: ./apps/prod
  prune: true
  wait: true

